# Generated by Django 5.2.1 on 2025-06-02 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.FilePathField(allow_files=False, allow_folders=True)),
                ('timezone', models.CharField(default='Europe/Oslo', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('file', models.FilePathField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordings.camera')),
            ],
        ),
    ]
