# Generated by Django 5.2.1 on 2025-06-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True, path=None),
        ),
        migrations.AlterUniqueTogether(
            name='recording',
            unique_together={('camera', 'start_time')},
        ),
    ]
