# Generated by Django 5.2.1 on 2025-06-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_alter_camera_path_alter_recording_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recording',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterField(
            model_name='recording',
            name='file',
            field=models.FilePathField(unique=True),
        ),
    ]
