# Generated by Django 5.2.2 on 2025-06-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0003_alter_recording_options_alter_recording_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='mtime',
            field=models.DateTimeField(null=True),
        ),
    ]
